### ISSUE TITLE
建行生活报错

### ISSUE THREAD

**Issue by niceqishi** [FoKit/Scripts#13]
大佬 建行生活报错 重启无效
{"errCode":"470","errMsg":"该功能检查到有新版本,请尝试重启APP体验。"}
TypeError: Cannot read properties of undefined (reading 'length')
    at hideSensitiveData (/ql/scripts/raw_scripts_jhsh_checkIn.js:287:32)
    at /ql/scripts/raw_scripts_jhsh_checkIn.js:224:29
    at got.<computed>.then.message (/ql/scripts/raw_scripts_jhsh_checkIn.js:311:7281)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
❌ 账号 [1] 签到失败，该功能检查到有新版本,请尝试重启APP体验。

**Comment by Raphael689** [comment]
loon也报错
{"errCode":"470","errMsg":"该功能检查到有新版本,请尝试重启APP体验。"}
{
}
❌ 账号 [1] 签到失败，该功能检查到有新版本,请尝试重启APP体验。

**Comment by FoKit** [comment]
请更新脚本重新获取签到数据
