### ISSUE TITLE
伊利ck

### ISSUE THREAD

**Issue by a1564471347** [FoKit/Scripts#7]
变量不是id77_yiLi_cookies吗？青龙提示未获取cookie，手机上却可以识别到

**Comment by FoKit** [comment]
已兼容 Node.js 环境，请更新脚本。

**Comment by a1564471347** [comment]
/ql/data/scripts/raw_scripts-310
let users = $• getData ($. COOKIES_KEY) ;
TypeError: $•getData is not a function
at Object.<anonymous> (/ql/data/scripts/raw_scripts_
yili. js:10:15)
at Module._compile (node: internal/modules/cjs/loade
r: 1256:14)
at Module-_extensions. js (node: internal/modules/cj
s/loader: 1310:10)
at Module. load (node: internal/modules/cjs/loader:111
9:32）
at Module._load (node: internal/modules/cjs/loader: 96
0:12）
at Function. executeUserEntryPoint [as runMain] (nod
e: internal/modules/ run_main: 81:12)
at node: internal/main/ run_main_module:23:47
Node. js v18.17.0
## 执行结束••2023-08-19 12:17:03
耗时1秒
什么情况？

**Comment by FoKit** [comment]
已修复

**Comment by a1564471347** [comment]
> 已修复

伊利乳品, 错误!
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at XMLtoJson (/ql/data/scripts/raw_scripts_yiLi.js:625:15)
    at /ql/data/scripts/raw_scripts_yiLi.js:164:16
    at /ql/data/scripts/raw_scripts_yiLi.js:635:7404
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
========undefined=====

❗️伊利乳品, 错误!
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at XMLtoJson (/ql/data/scripts/raw_scripts_yiLi.js:625:15)
    at /ql/data/scripts/raw_scripts_yiLi.js:206:16
    at /ql/data/scripts/raw_scripts_yiLi.js:635:7404
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
出现新错误

**Comment by FoKit** [comment]
测试正常运行，请检查 Cookie 格式。

**Comment by a1564471347** [comment]
> 测试正常运行，请检查 Cookie 格式。

什么格式，我用原作者的重写获取的

**Comment by FoKit** [comment]
Cookie 格式与 boxjs 数据一致

**Comment by a1564471347** [comment]
> Cookie 格式与 boxjs 数据一致

我就是复制boxjs里面获取的ck

**Comment by FoKit** [comment]
export id77_yiLi_cookies='{"xxx":{"aspnetUserId":"xxx","UserName":"18888888888","AccountType":4,"UserInRoles":["网站会员"],"IsAnonymous":false,"StaffID":0,"StaffName":"xxx","StaffMobile":"18888888888","StaffPosition":0,"StaffPositionName":"","ClientID":12345,"ClientName":"xxx","OwnerType":0,"OrganizeCity":0,"ClientType":4,"RelateManufaturer":0,"RelateManufaturerName":"","DeviceCode":"DeviceCode","AppVersion":"","authKey":"xxx"}}'
